name: CI test

on:
  push:
    branches: [ "githubactions" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get list of changed files
        id: files
        run: |
          echo "::set-output name=files::$(git diff --name-only origin/main)"
      - name: Check for keywords
        id: check_keywords
        run: |
          echo "${{ steps.files.outputs.files }}" > changed_files.txt
          if grep -E 'Main' changed_files.txt; then
            echo "trigger=true" >> $GITHUB_OUTPUT
          else
            echo "trigger=false" >> $GITHUB_OUTPUT
          fi

      - name: Send Slack message
        if: steps.check_keywords.outputs.trigger == 'true'
        run:
          echo "found the keyword"
