name: CI test

on:
  push:
    branches: [ "githubactions" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set output
        run: echo files=git diff --name-only origin/githubactionsmaster origin/${{ github.ref_name }} >> $GITHUB_OUTPUT
      - name: Check for keywords
        id: check_keywords
        run: |
          echo $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT > changed_files.txt
          if grep -E 'Main' changed_files.txt; then
            echo "trigger=true" >> $GITHUB_OUTPUT
          else
            echo "trigger=false" >> $GITHUB_OUTPUT
          fi

      - name: Send Slack message
        if: steps.check_keywords.outputs.trigger == 'true'
        run:
          echo "found the keyword"
